# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betslip_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='betslip',
            old_name='possibiltiy',
            new_name='possibility',
        ),
    ]
