# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betslip_app', '0003_auto_20171019_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='betslip',
            name='possibility',
        ),
        migrations.AddField(
            model_name='match',
            name='possibility',
            field=models.FloatField(null=True),
        ),
    ]
